version: 2.1

orbs:
  python: circleci/python@0.2.1
  jira: circleci/jira@1.1.7

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pipenv run python test/test_math.py
          name: Test
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
          
workflows:
  main:
    jobs:
      - build-and-test
